controllers/CanchasController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\Canchas;
use app\models\CanchasSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\models\UploadForm;
use yii\web\UploadedFile;
use yii\db\Query;

/**
 * CanchasController implements the CRUD actions for Canchas model.
 */
class CanchasController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['Administrador'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Canchas models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CanchasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Canchas model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Canchas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Canchas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_cancha]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Canchas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save(false)) {
            return $this->redirect(['view', 'id' => $model->id_cancha]);
        } else {
            $query = new Query;
            $estados = $query->select('*')->from('estados')->where('entidad = "canchas"')->all();
            return $this->render('update', [
                'model' => $model,
                'estados' => $estados,
            ]);
        }
    }

    /**
     * Deletes an existing Canchas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $cancha = $this->findModel($id);
        if($cancha->imagen_logo !== 'default.jpg'){
            unlink('images/logos/'.$cancha->imagen_logo);
        }
        if($cancha->imagen_cancha !== 'default.jpg'){
            unlink('images/canchas/'.$cancha->imagen_cancha);
        }
        $cancha->delete();

        return $this->redirect(['index']);
    }

    public function actionUpload()
    {
        $model = new UploadForm();
        if ($model->load(Yii::$app->request->post())) {
            $model->file = UploadedFile::getInstance($model, 'file');
            if ($model->validate()) {
                $cancha = $this->findModel($model->cancha);
                $nombre_archivo = md5(time()).'.'. $model->file->extension;
                if($model->destino === 'logos'){
                    if($cancha->imagen_logo !== 'default.jpg'){
                        unlink('images/logos/'.$cancha->imagen_logo);
                    }
                    $cancha->imagen_logo = $nombre_archivo;
                }else{
                    if($cancha->imagen_cancha !== 'default.jpg'){
                        unlink('images/canchas/'.$cancha->imagen_cancha);
                    }
                    $cancha->imagen_cancha = $nombre_archivo;
                }
                // $mask = 'images/'.$model->destino.'/'.$model->cancha.'*.*';
                // array_map('unlink', glob($mask));
                // $model->file->saveAs('images/'.$model->destino.'/'.$model->cancha.'.'. $model->file->extension);
                $model->file->saveAs('images/'.$model->destino.'/'.$nombre_archivo);
                $cancha->save(false);
            }
        }
        return $this->redirect(['view', 'id' => $model->cancha, 'status' => '1']);
    }

    /**
     * Finds the Canchas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Canchas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Canchas::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/EstadosController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\Estados;
use app\models\EstadosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * EstadosController implements the CRUD actions for Estados model.
 */
class EstadosController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['Administrador'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Estados models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EstadosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Estados model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Estados model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Estados();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_estado]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Estados model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_estado]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Estados model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Estados model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Estados the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Estados::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/layoutLogin.php
<?php

use yii\helpers\Html;
use app\assets\AppAsset;
AppAsset::register($this);
$this->beginPage();
?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
	<head>
		<meta charset="<?= Yii::$app->charset ?>" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" type="image/png" href="<?= Yii::$app->request->baseUrl; ?>/images/favicon.ico" />
		<script type="text/javascript" charset="utf8" src="<?= Yii::$app->request->baseUrl; ?>/js/jquery.min.js"></script>
		<?= Html::csrfMetaTags() ?>
		<title><?= Html::encode($this->title) ?></title>
		<?php $this->head() ?>
	</head>

	<body>
		<?php $this->beginBody() ?>
		<div class="container"><br><br>
			<?= $content; ?>
		</div>
		<?php $this->endBody() ?>
	</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="<?= Yii::$app->request->baseUrl; ?>/images/favicon.ico" />
    <?= Html::csrfMetaTags() ?>
    <script type="text/javascript" charset="utf8" src="<?= Yii::$app->request->baseUrl; ?>/js/jquery.min.js"></script>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>
    <div class="wrap">
        
        <?php
            NavBar::begin([
                'brandLabel' => '<a class="navbar-brand" href="'.Yii::$app->homeUrl.'"><img alt="Brand" src="'.Yii::$app->request->baseUrl.'/images/icono.png">&nbspFútbol Cracks</a>',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    Yii::$app->user->isGuest ?
                    ['label' => ''] :
                    ['label' => 'Canchas',
                        'items' => [
                            ['label' => 'Crear cancha', 'url' => ['/canchas/create']],
                            ['label' => 'Listar canchas', 'url' => ['/canchas/index']],
                        ],
                    ],
                    Yii::$app->user->isGuest ?
                    ['label' => ''] :
                    ['label' => 'Partidos',
                        'items' => [
                            ['label' => 'Crear partido', 'url' => ['/partidos/create']],
                            ['label' => 'Listar partidos', 'url' => ['/partidos/index']],
                        ],
                    ],
                    Yii::$app->user->isGuest ?
                    ['label' => ''] :
                    ['label' => 'Usuarios',
                        'items' => [
                            ['label' => 'Crear usuario', 'url' => ['/usuarios/create']],
                            ['label' => 'Listar usuarios', 'url' => ['/usuarios/index']],
                        ],
                    ],
                    Yii::$app->user->isGuest ?
                    ['label' => ''] :
                    ['label' => 'Estados',
                        'items' => [
                            ['label' => 'Crear estado', 'url' => ['/estados/create']],
                            ['label' => 'Listar estados', 'url' => ['/estados/index']],
                        ],
                    ],
                    Yii::$app->user->isGuest ?
                    ['label' => ''] :
                    ['label' => 'Consulta', 'url' => ['/consulta/index']],
                    Yii::$app->user->isGuest ?
                        ['label' => ''] :
                        [
                            'label' => 'Mi perfil',
                            'items' => [
                                ['label' => 'Mi perfil', 'url' => ['/usuarios/view?id='.Yii::$app->user->id]],
                                ['label' => 'Salir (' . Yii::$app->user->identity->username . ')',
                                    'url' => ['/site/logout'],
                                    'linkOptions' => ['data-method' => 'post']],
                            ]
                        ]
                ],
            ]);
            NavBar::end();
        ?>

        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="pull-left">&copy; Fútbol Cracks <?= date('Y') ?></p>
            <p class="pull-right">Powered by Elecsis</p>
        </div>
    </footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>